# This manifest is a list of shared workarounds that are needed in NestOS

postprocess:
  - |
    #!/usr/bin/env bash
    set -xeuo pipefail
    mkdir /etc/issue.d
    export OSTREEVERSION="$(tail -1 /etc/os-release)"
    source /etc/os-release
    export K8SVERSION="VERSION="$OSTREE_VERSION""
    export K8SPRETTY_NAME="PRETTY_NAME=\"NestOS $OSTREE_VERSION\""
    echo -e 'NAME="NestOS"'> /usr/lib/os-release 
    echo -e $K8SVERSION >> /usr/lib/os-release 
    echo -e 'ID="NestOS"\nVERSION_ID="22.03-LTS-SP2"\n' >> /usr/lib/os-release
    echo -e $K8SPRETTY_NAME >> /usr/lib/os-release
    echo -e 'ANSI_COLOR="0;31"\nHOME_URL="https://nestos.openeuler.org/"\nDOCUMENTATION_URL="https://nestos.openeuler.org/"\nSUPPORT_URL="https://nestos.openeuler.org/"\nBUG_REPORT_URL="https://nestos.openeuler.org/"\nVARIANT="NestOS"\nVARIANT_ID=nestos\n' >> /usr/lib/os-release
    echo -e $OSTREEVERSION >> /usr/lib/os-release 
    cat > /usr/lib/dracut/modules.d/40network/module-setup.sh <<'EOF'
    #!/bin/bash
    
    # called by dracut
    check() {
        return 255
    }
    
    # called by dracut
    depends() {
        is_qemu_virtualized && echo -n "qemu-net "
    
        for module in network-wicked network-manager network-legacy; do
            if dracut_module_included "$module"; then
                network_handler="$module"
                break
            fi
        done
    
        if [ -z "$network_handler" ]; then
            if [[ -x $dracutsysrootdir$systemdsystemunitdir/wicked.service ]]; then
                network_handler="network-wicked"
            elif [[ -x $dracutsysrootdir/usr/libexec/nm-initrd-generator ]]; then
                network_handler="network-manager"
            else
                network_handler="network-legacy"
            fi
        fi
        echo "kernel-network-modules $network_handler"
        return 0
    }
    
    # called by dracut
    installkernel() {
        return 0
    }

    # called by dracut
    install() {
        inst_script "$moddir/netroot.sh" "/sbin/netroot"
        inst_simple "$moddir/net-lib.sh" "/lib/net-lib.sh"
        inst_hook pre-udev 50 "$moddir/ifname-genrules.sh"
        inst_hook cmdline 91 "$moddir/dhcp-root.sh"
        inst_multiple ip sed awk grep pgrep tr
        inst_multiple -o arping arping2
        dracut_need_initqueue
    }
    EOF
    chmod +x /usr/lib/dracut/modules.d/40network/module-setup.sh