
packages:
  # Basic user tools
  ## jq - parsing/interacting with JSON data
  - bash-completion
  - coreutils
  - jq
  #- nano
  - less
  - sudo
  - vim-minimal
  # File compression/decompression
  ## bsdtar - dependency of 35coreos-live dracut module
  - bsdtar
  - bzip2
  - gzip
  - tar
  - xz
  # Improved MOTD experience
  - console-login-helper-messages-issuegen
  - console-login-helper-messages-profile
  # kdump support
  - kexec-tools
  # Remote Access
  - openssh-clients openssh-server
  # Container tooling
  - podman
  - crio
  - cri-tools
  - docker-runc
  - skopeo
  - toolbox
